name: Refresh Pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empty commit
        run: git commit --allow-empty -m "Empty commit"
